# Generated by Django 5.2.4 on 2025-08-30 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_to',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', through='notes.NoteShare', to=settings.AUTH_USER_MODEL),
        ),
    ]
