# Generated by Django 5.2.4 on 2025-08-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_shared_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
    ]
